name: Upload File to S3

on:
  push:
    branches:
      - main  # You can change this to the branch you want to trigger the action on

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your desired AWS region

      # Step 3: Upload file to S3
      - name: Upload file to S3
        run: |
          aws s3 cp ./home/anu/Desktop/hi.txt s3://anubhello.123/Buckets/anubhello.123/
